// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatProcessDisplayName(arg1) {
  return window['go']['procs']['Procs']['FormatProcessDisplayName'](arg1);
}

export function GetProcesses(arg1) {
  return window['go']['procs']['Procs']['GetProcesses'](arg1);
}

export function SetContext(arg1) {
  return window['go']['procs']['Procs']['SetContext'](arg1);
}

export function VerifyProcessesState(arg1) {
  return window['go']['procs']['Procs']['VerifyProcessesState'](arg1);
}
