// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {procs} from '../models';
import {context} from '../models';

export function FormatProcessDisplayName(arg1:string):Promise<string>;

export function GetProcesses(arg1:Array<procs.BaseProcess>):Promise<Array<procs.BaseProcess>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function VerifyProcessesState(arg1:Array<procs.BaseProcess>):Promise<Array<procs.BaseProcess>>;
