// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDatabase() {
  return window['go']['procsDal']['ProcsDal']['CloseDatabase']();
}

export function CreateOrLoadDatabase() {
  return window['go']['procsDal']['ProcsDal']['CreateOrLoadDatabase']();
}

export function GetAllTrackedProcess() {
  return window['go']['procsDal']['ProcsDal']['GetAllTrackedProcess']();
}

export function InsertNewTrackedProcess(arg1) {
  return window['go']['procsDal']['ProcsDal']['InsertNewTrackedProcess'](arg1);
}

export function OpenDatabase() {
  return window['go']['procsDal']['ProcsDal']['OpenDatabase']();
}

export function SetContext(arg1) {
  return window['go']['procsDal']['ProcsDal']['SetContext'](arg1);
}
