// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDatabase() {
  return window['go']['procsDal']['ProcsDal']['CloseDatabase']();
}

export function CreateOrLoadDatabase() {
  return window['go']['procsDal']['ProcsDal']['CreateOrLoadDatabase']();
}

export function GetAllTrackedProcess() {
  return window['go']['procsDal']['ProcsDal']['GetAllTrackedProcess']();
}

export function GetTrackedProcessImage(arg1) {
  return window['go']['procsDal']['ProcsDal']['GetTrackedProcessImage'](arg1);
}

export function InsertNewTrackedProcess(arg1) {
  return window['go']['procsDal']['ProcsDal']['InsertNewTrackedProcess'](arg1);
}

export function InsertOrUpdateNewTrackedProcessImage(arg1, arg2) {
  return window['go']['procsDal']['ProcsDal']['InsertOrUpdateNewTrackedProcessImage'](arg1, arg2);
}

export function OpenDatabase() {
  return window['go']['procsDal']['ProcsDal']['OpenDatabase']();
}

export function SetContext(arg1) {
  return window['go']['procsDal']['ProcsDal']['SetContext'](arg1);
}

export function StopTrackingProcess(arg1) {
  return window['go']['procsDal']['ProcsDal']['StopTrackingProcess'](arg1);
}

export function UpdateTrackedProcessName(arg1, arg2) {
  return window['go']['procsDal']['ProcsDal']['UpdateTrackedProcessName'](arg1, arg2);
}
