// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrLoadDatabase() {
  return window['go']['procsDal']['ProcsDal']['CreateOrLoadDatabase']();
}

export function SetContext(arg1) {
  return window['go']['procsDal']['ProcsDal']['SetContext'](arg1);
}
